version: '3'

services:
  finale:
    image: cyberwizard1/facial_server:1
    devices:
        - /dev/video0:/dev/video0
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
    environment: 
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: 1
    tty: true    
    stdin_open: true
    ports:
        - 5000:5000
